name: "ollama"
services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - D:/GenAI/genai/ollama/models:/root/.ollama/models
      
volumes:
  models: